---

- name: configuration
  hosts: ab-logstash
  become: yes
  roles:
    - apt
    - timezone
    - ntp_update
    - monit
    - geerlingguy.java
    - geerlingguy.elasticsearch
    - geerlingguy.logstash
    - ini
 
  vars:
    es_plugins:
      - plugin: elasticsearch/elasticsearch-cloud-aws/2.4.2
      - plugin: mobz/elasticsearch-head
      - plugin: royrusso/elasticsearch-HQ/v1.0.0
#    es_api_basic_auth_username: admin
#    es_api_basic_auth_password: admin
    es_instance_name: "node1"
    es_heap_size: "256m"
    tags: [geerlingguy.elasticsearch]
 
